#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v10
# autospec commit: 5905be9
#
# Source0 file verified with key 0x7FD9FCCB000BEEEE (meyering@fb.com)
#
Name     : automake
Version  : 1.16.5
Release  : 31
URL      : https://mirrors.kernel.org/gnu/automake/automake-1.16.5.tar.xz
Source0  : https://mirrors.kernel.org/gnu/automake/automake-1.16.5.tar.xz
Source1  : https://mirrors.kernel.org/gnu/automake/automake-1.16.5.tar.xz.sig
Source2  : 7FD9FCCB000BEEEE.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: automake-bin = %{version}-%{release}
Requires: automake-data = %{version}-%{release}
Requires: automake-info = %{version}-%{release}
Requires: automake-license = %{version}-%{release}
Requires: automake-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : cscope
BuildRequires : ctags
BuildRequires : expect
BuildRequires : flex
BuildRequires : gfortran
BuildRequires : gnupg
BuildRequires : perl(Getopt::Long)
BuildRequires : pypi-docutils
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is Automake, a Makefile generator.  It aims to be portable and
to conform to the GNU Coding Standards for Makefile variables and
targets.

%package bin
Summary: bin components for the automake package.
Group: Binaries
Requires: automake-data = %{version}-%{release}
Requires: automake-license = %{version}-%{release}

%description bin
bin components for the automake package.


%package data
Summary: data components for the automake package.
Group: Data
Requires: perl(Getopt::Long)

%description data
data components for the automake package.


%package dev
Summary: dev components for the automake package.
Group: Development
Requires: automake-bin = %{version}-%{release}
Requires: automake-data = %{version}-%{release}
Provides: automake-devel = %{version}-%{release}
Requires: automake = %{version}-%{release}

%description dev
dev components for the automake package.


%package doc
Summary: doc components for the automake package.
Group: Documentation
Requires: automake-man = %{version}-%{release}
Requires: automake-info = %{version}-%{release}

%description doc
doc components for the automake package.


%package info
Summary: info components for the automake package.
Group: Default

%description info
info components for the automake package.


%package license
Summary: license components for the automake package.
Group: Default

%description license
license components for the automake package.


%package man
Summary: man components for the automake package.
Group: Default

%description man
man components for the automake package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 7FD9FCCB000BEEEE' gpg.status
%setup -q -n automake-1.16.5
cd %{_builddir}/automake-1.16.5
pushd ..
cp -a automake-1.16.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713224139
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1713224139
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/automake
cp %{_builddir}/automake-%{version}/COPYING %{buildroot}/usr/share/package-licenses/automake/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/automake-%{version}/lib/COPYING %{buildroot}/usr/share/package-licenses/automake/31a3d460bb3c7d98845187c716a30db81c44b615 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/aclocal
/usr/bin/aclocal-1.16
/usr/bin/automake
/usr/bin/automake-1.16

%files data
%defattr(-,root,root,-)
/usr/share/aclocal-1.16/internal/ac-config-macro-dirs.m4
/usr/share/aclocal/README
/usr/share/automake-1.16/Automake/ChannelDefs.pm
/usr/share/automake-1.16/Automake/Channels.pm
/usr/share/automake-1.16/Automake/Condition.pm
/usr/share/automake-1.16/Automake/Config.pm
/usr/share/automake-1.16/Automake/Configure_ac.pm
/usr/share/automake-1.16/Automake/DisjConditions.pm
/usr/share/automake-1.16/Automake/FileUtils.pm
/usr/share/automake-1.16/Automake/General.pm
/usr/share/automake-1.16/Automake/Getopt.pm
/usr/share/automake-1.16/Automake/Item.pm
/usr/share/automake-1.16/Automake/ItemDef.pm
/usr/share/automake-1.16/Automake/Language.pm
/usr/share/automake-1.16/Automake/Location.pm
/usr/share/automake-1.16/Automake/Options.pm
/usr/share/automake-1.16/Automake/Rule.pm
/usr/share/automake-1.16/Automake/RuleDef.pm
/usr/share/automake-1.16/Automake/VarDef.pm
/usr/share/automake-1.16/Automake/Variable.pm
/usr/share/automake-1.16/Automake/Version.pm
/usr/share/automake-1.16/Automake/Wrap.pm
/usr/share/automake-1.16/Automake/XFile.pm
/usr/share/automake-1.16/COPYING
/usr/share/automake-1.16/INSTALL
/usr/share/automake-1.16/am/check.am
/usr/share/automake-1.16/am/check2.am
/usr/share/automake-1.16/am/clean-hdr.am
/usr/share/automake-1.16/am/clean.am
/usr/share/automake-1.16/am/compile.am
/usr/share/automake-1.16/am/configure.am
/usr/share/automake-1.16/am/data.am
/usr/share/automake-1.16/am/dejagnu.am
/usr/share/automake-1.16/am/depend.am
/usr/share/automake-1.16/am/depend2.am
/usr/share/automake-1.16/am/distdir.am
/usr/share/automake-1.16/am/footer.am
/usr/share/automake-1.16/am/header-vars.am
/usr/share/automake-1.16/am/header.am
/usr/share/automake-1.16/am/inst-vars.am
/usr/share/automake-1.16/am/install.am
/usr/share/automake-1.16/am/java.am
/usr/share/automake-1.16/am/lang-compile.am
/usr/share/automake-1.16/am/lex.am
/usr/share/automake-1.16/am/library.am
/usr/share/automake-1.16/am/libs.am
/usr/share/automake-1.16/am/libtool.am
/usr/share/automake-1.16/am/lisp.am
/usr/share/automake-1.16/am/ltlib.am
/usr/share/automake-1.16/am/ltlibrary.am
/usr/share/automake-1.16/am/mans-vars.am
/usr/share/automake-1.16/am/mans.am
/usr/share/automake-1.16/am/program.am
/usr/share/automake-1.16/am/progs.am
/usr/share/automake-1.16/am/python.am
/usr/share/automake-1.16/am/remake-hdr.am
/usr/share/automake-1.16/am/scripts.am
/usr/share/automake-1.16/am/subdirs.am
/usr/share/automake-1.16/am/tags.am
/usr/share/automake-1.16/am/texi-vers.am
/usr/share/automake-1.16/am/texibuild.am
/usr/share/automake-1.16/am/texinfos.am
/usr/share/automake-1.16/am/vala.am
/usr/share/automake-1.16/am/yacc.am
/usr/share/automake-1.16/ar-lib
/usr/share/automake-1.16/compile
/usr/share/automake-1.16/config.guess
/usr/share/automake-1.16/config.sub
/usr/share/automake-1.16/depcomp
/usr/share/automake-1.16/install-sh
/usr/share/automake-1.16/mdate-sh
/usr/share/automake-1.16/missing
/usr/share/automake-1.16/mkinstalldirs
/usr/share/automake-1.16/py-compile
/usr/share/automake-1.16/tap-driver.sh
/usr/share/automake-1.16/test-driver
/usr/share/automake-1.16/texinfo.tex
/usr/share/automake-1.16/ylwrap

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal-1.*/*.m4

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/automake/*

%files info
%defattr(0644,root,root,0755)
/usr/share/info/automake-history.info
/usr/share/info/automake.info
/usr/share/info/automake.info-1
/usr/share/info/automake.info-2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/automake/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/automake/31a3d460bb3c7d98845187c716a30db81c44b615

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/aclocal-1.16.1
/usr/share/man/man1/aclocal.1
/usr/share/man/man1/automake-1.16.1
/usr/share/man/man1/automake.1
